dc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_change

from dashboard.views import DashboardView
from dc import settings
from users.views import EmailChangeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^email_change/$', EmailChangeView.as_view(), name='email_change'),
    url(r'^password_change/$', password_change, {'template_name': 'registration/password_change_form.html',
                                                 'post_change_redirect': 'dashboard'}, name='password_change'),

    url('^', include('django.contrib.auth.urls')),
    url('^users/', include('users.urls')),
    url('^messages/', include('alert_messages.urls')),
    url('^cards/', include('cards.urls')),
    url('^finance/', include('finance.urls')),
    url('^agreements/', include('agreements.urls')),
    url('^stantions/', include('stantions.urls')),
    url('^support/', include('support.urls', namespace='support')),

    url('^api/messages/', include('alert_messages.urls_api')),
    url('^api/cards/', include('cards.urls_api')),
    url('^api/users/', include('users.urls_api')),
    url('^api/support/', include('support.urls', namespace='support_api')),

    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', TransactionListView.as_view(), name='finance_child_pays_list'),
    url(r'^my$', MyTransactionListView.as_view(), name='finance_my_pays_list'),
    url(r'^pay$', PayView.as_view(), name='finance_pay'),
    url(r'^stat$', StatisticsView.as_view(), name='finance_stat'),
    url(r'^dynamics$', StatDynamicView.as_view(), name='finance_stat_dynamic'),
]

finance/models.py
from django.db import models

from cards.models import Request
from cards.utils import get_price_field_for_category
from users.models import MyUser


class TransactionManager(models.Manager):
    def create_request_debit_for_tree(self, user: MyUser, request: Request, action: int=2):
        transactions = list()
        user_price_field = get_price_field_for_category(request.ts_category)

        for ancestors in user.get_ancestors(include_self=True).select_related('parent'):
            if action == 2:
                cost = getattr(ancestors.parent, user_price_field) if ancestors.parent_id else 0
                subtotal = getattr(ancestors, user_price_field)
            else:
                cost = 0
                subtotal = 0
            transactions.append(Transaction(user_id=ancestors.pk, status=1, action=2, request=request, cost=cost,
                                            subtotal=subtotal, user_parent_id=ancestors.parent_id))
        return self.bulk_create(transactions)


class Transaction(models.Model):
    STATUSES = (
        (1, 'Создана'),
        (2, 'В процессе'),
        (3, 'Исполнена'),
        (4, 'Отменена'),
    )

    ACTIONS_CHOICES = (
        (1, 'Пополнение баланса'),
        (2, 'Списание за заявку'),
        (3, 'Дубликат заявки'),
    )

    date_created = models.DateTimeField('Дата создания', auto_now_add=True)
    user_parent = models.ForeignKey(MyUser, related_name='transactions_user_parent', null=True)
    user = models.ForeignKey(MyUser)
    status = models.IntegerField('Статус', choices=STATUSES, default=1)
    action = models.IntegerField('Действие', choices=ACTIONS_CHOICES)
    request = models.ForeignKey(Request, blank=True, null=True, related_name='transactions')
    cost = models.DecimalField('Стоимость', decimal_places=0, max_digits=10, default=0)
    subtotal = models.DecimalField('Сумма', decimal_places=0, max_digits=10, default=0)

    objects = TransactionManager()

    def __str__(self):
        return "{}: {}".format(self.date_created.strftime('%H:%M%S %d.%m.%Y'), self.get_action_display())

    class Meta:
        ordering = ('-pk',)

    def done(self, commit=True):
        if self.action == 1:
            self.user.increment_balance(self.subtotal)
            # hide pay alert
            from alert_messages.models import Message
            Message.objects.filter(to_user_id=self.user_id, is_pay_alert_hide=False).update(is_pay_alert_hide=True)
        elif self.action == 2:
            self.user.decrement_balance(self.subtotal)
        self.status = 3
        if commit:
            self.save()

    def cancel(self, commit=True):
        self.status = 4
        if commit:
            self.save()

cards/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _

from cards.models import Request


class RequestEditForm(forms.ModelForm):
    ts_vin = forms.CharField(label='VIN', required=False, min_length=17, max_length=17,
                             help_text='Если отсутствует, то не заполняется',
                             validators=[RegexValidator('^[0-9A-HJ-NPR-Za-hj-npr-z]+$',
                                                        message='Введен запрещенный символ')])

    class Meta:
        model = Request
        fields = ('user_type', 'is_foreign', 'user_last_name', 'user_first_name', 'user_middle_name', 'org_title', 'user_contact',
                  'doc_type', 'doc_serial', 'doc_num', 'doc_issued_date', 'doc_issued_by',
                  'ts_category', 'ts_sub_category', 'ts_reg_num', 'ts_vin', 'ts_body_num', 'ts_frame_num', 'ts_mark',
                  'ts_model', 'ts_year', 'ts_mass_base', 'ts_mass_max', 'ts_mileage', 'ts_fuel_type', 'ts_brakes_type',
                  'ts_tyre_vendor', 'ts_taxi', 'ts_training', 'ts_dangerous', 'ts_dual_fuel', 'notes',)

    def clean(self):
        cleaned_data = super().clean()

        # org_title required if user_type == 2
        user_type = cleaned_data.get('user_type')
        if user_type == 2 and not cleaned_data.get('org_title'):
            self.add_error('org_title', _('This field is required.'))

        ts_category = cleaned_data.get('ts_category')
        # ts_mileage is required if ts_category != E
        if ts_category != 5 and not cleaned_data.get('ts_mileage'):
            self.add_error('ts_mileage', _('This field is required.'))

        # ts_fuel_type is required if ts_category != E
        if ts_category != 5 and not cleaned_data.get('ts_fuel_type'):
            self.add_error('ts_fuel_type', _('This field is required.'))

        # ts_sub_category is required for category B
        if ts_category == 2 and not cleaned_data.get('ts_sub_category'):
            self.add_error('ts_sub_category', _('This field is required.'))

        ts_mass_base = cleaned_data.get('ts_mass_base')
        ts_mass_max = cleaned_data.get('ts_mass_max')
        if ts_mass_base and ts_mass_max and ts_mass_base > ts_mass_max:
            self.add_error('ts_mass_max', 'Значение не может быть меньше чем Масса без нагрузки')

        return cleaned_data


class RequestDeleteForm(forms.Form):
    delete = forms.BooleanField(initial=True, widget=forms.HiddenInput)


class RequestSearchFrom(forms.Form):
    SEARCH_FIELD_CHOICES = (
        ('ts_vin', 'VIN'),
        ('diagcard_num', 'Номер карты'),
        ('ts_reg_num', 'Регистрационный номер'),
    )

    user = forms.MultipleChoiceField(label='Агент', choices=(), required=False)
    search_field = forms.ChoiceField(label='Поле поиска', choices=SEARCH_FIELD_CHOICES)
    search_value = forms.CharField(label='&nbsp;', required=False)
    daterange_start = forms.DateField(label='с', input_formats=['%d.%m.%Y'], required=False)
    daterange_end = forms.DateField(label='по', input_formats=['%d.%m.%Y'], required=False)

    def __init__(self, user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].choices = user_qs


class ExportMyForm(forms.Form):
    FIELD_CHOICES = (
        ('pk', '№ заявки'),
        ('date_send', 'Дата отправки'),
        ('ts_category', 'Категория'),
        ('ts_mark', 'Марка'),
        ('ts_model', 'Модель'),
        ('price', 'Цена'),
        ('user', 'Владелец'),
        ('ts_reg_num', 'Регистрационный знак'),
        ('diagcard_num', 'Номер карты'),
    )

    daterange_start = forms.DateTimeField(label='с', input_formats=['%d.%m.%Y %H:%M'], required=True)
    daterange_end = forms.DateTimeField(label='по', input_formats=['%d.%m.%Y %H:%M'], required=True)
    export_fields = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=FIELD_CHOICES,
                                              initial={'pk': True}, label='Поле для экспорта')


class ExportChildForm(ExportMyForm):
    FIELD_CHOICES = ExportMyForm.FIELD_CHOICES + (
        ('author', 'Агент'),
    )

    user = forms.MultipleChoiceField(label='Агент', choices=(), required=False, widget=forms.CheckboxSelectMultiple)
    export_fields = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=FIELD_CHOICES,
                                              initial={'pk': True}, label='Поле для экспорта')

    def __init__(self, user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].choices = user_qs


class StatForm(forms.Form):
    daterange_start = forms.DateTimeField(label='с', input_formats=['%d.%m.%Y %H:%M'], required=True)
    daterange_end = forms.DateTimeField(label='по', input_formats=['%d.%m.%Y %H:%M'], required=True)


class CardSearchForm(forms.Form):
    ts_vin = forms.CharField(label='VIN', required=False, max_length=255,
                             validators=[RegexValidator('^[0-9A-HJ-NPR-Za-hj-npr-z]+$',
                                                        message='Введен запрещенный символ')])
    ts_reg_num = forms.CharField(label='Регистрационный номер', required=False, max_length=100)
    diagcard_num = forms.CharField(label='Номер карты', max_length=255, required=False)

    def clean(self):
        if not self.cleaned_data['ts_vin'] and not self.cleaned_data['ts_reg_num'] \
                and not self.cleaned_data['diagcard_num']:
            raise forms.ValidationError('Должно быть заполнено одно из полей.')


class CardSearchMassForm(forms.Form):
    diagcard_num = forms.CharField(label='Номера карт', widget=forms.Textarea(attrs={'rows': 5}),
                                   help_text='Введите номера карт. В каждой строке 1 номер карты.')

    def clean_diagcard_num(self):
        diagcard_num = self.cleaned_data['diagcard_num']
        if diagcard_num:
            card_nums = []
            for num in diagcard_num.split():
                if num.strip():
                    card_nums.append(num.strip())
            return card_nums
        else:
            return [diagcard_num]

finance/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from finance.models import Transaction
from users.models import MyUser


class DateSearchForm(forms.Form):
    daterange_start = forms.DateField(label='с', input_formats=['%d.%m.%Y'], required=False)
    daterange_end = forms.DateField(label='по', input_formats=['%d.%m.%Y'], required=False)


class MyTransactionSearchFrom(DateSearchForm):
    pass


class TransactionSearchFrom(DateSearchForm):
    user = forms.MultipleChoiceField(label='Агент', choices=(), required=False)

    def __init__(self, user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].choices = user_qs


class StatSearchFrom(DateSearchForm):
    daterange_start = forms.DateTimeField(label='с', input_formats=['%d.%m.%Y %H:%M'])
    daterange_end = forms.DateTimeField(label='по', input_formats=['%d.%m.%Y %H:%M'])
    user = forms.ChoiceField(label='Агент', choices=(), required=False)

    def __init__(self, user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].choices = user_qs


class StatDynamicSearchFrom(forms.Form):
    GROUPBY_CHOICES = (
        ('day', 'По дням'),
        ('month', 'По месяцам'),
    )

    daterange_start = forms.DateField(label='с', input_formats=['%d.%m.%Y'])
    daterange_end = forms.DateField(label='по', input_formats=['%d.%m.%Y'])
    user = forms.ChoiceField(label='Агент', choices=(), required=False)
    groupby = forms.ChoiceField(label='Группировка', choices=GROUPBY_CHOICES, required=True)

    def __init__(self, user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].choices = user_qs


class TransactionCreateFrom(forms.ModelForm):
    user = forms.ModelChoiceField(label='Агент', queryset=MyUser.objects.none())

    def __init__(self, user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].queryset = user_qs

    class Meta:
        model = Transaction
        fields = ('user', 'subtotal',)


class TransactionCreateHierarchyForm(TransactionCreateFrom):
    user = TreeNodeChoiceField(label='Агент', queryset=MyUser.objects.none())

templates/finance/dynamic.html
{% extends 'layout.html' %}
{% block title %}Динамика продаж{% endblock %}

{% block content %}
<div class="request-search-page">
    <h2>Динамика продаж
        <abbr class="pull-right" data-toggle="popover" data-html="true" title="Помощь" data-placement="left" data-trigger="hover"
              data-content="В данном разделе можно отслеживать динамику продаж сотрудников по количеству и сумме за любой промежуток времени с группировкой по дням и месяцам."
        ><span class="fa fa-question-circle-o" ></span></abbr>
    </h2>
    <div class="well request-search">
        <form class="form-horizontal" method="post" id="requests_search_form">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-lg-3 col-md-4 col-xs-12">
                    <label for="id_search_value">Дата</label>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                        <input type="text" class="form-control" name="daterange" value="{% if form.daterange_start.value() and form.daterange_end.value() %}{{ form.daterange_start.value() }} - {{ form.daterange_end.value() }}{% endif %}">
                        <input type="hidden" id="id_daterange_start" name="daterange_start" value="{{ form.daterange_start.value() or '' }}">
                        <input type="hidden" id="id_daterange_end" name="daterange_end" value="{{ form.daterange_end.value() or '' }}">
                    </div>
                </div>
                {% if request.user.has_perm('cards.can_view_all') or request.user.has_perm('cards.can_view_all_child') %}
                <div class="col-lg-3 col-md-4 col-xs-12">
                    <label for="id_user">{{ form.user.label }}</label>
                    <select id="id_user" name="user" class="form-control">
                        {% for user in user_qs %}
                        <option value="{{ user[0] }}" {% if form.user.value() and user[0] == form.user.value() %}selected{% endif %}>{{ user[1] }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% endif %}
                <div class="col-lg-3 col-md-4 col-xs-12">
                    <label for="id_groupby">{{ form.groupby.label }}</label>
                    <select class="form-control" id="id_groupby" name="groupby" required="" tabindex="-1" aria-hidden="true">
                        <option value="day" {% if form.groupby.value() == 'day' %}selected{% endif %}>По дням</option>
                        <option value="month" {% if form.groupby.value() == 'month' %}selected{% endif %}>По месяцам</option>
                    </select>
                </div>
            </div>
            <div class="row form-submit">
                <div class="col-xs-12">
                    <button class="btn btn-primary btn-sm btn-fill" type="submit"><span class="fa fa-check"></span> Показать</button>
                </div>
            </div>
        </form>
    </div>
    <table class="table table-condensed table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>Агент</th>
        <th>Город</th>
        <th>Дата</th>
        <th>Кол-во</th>
        <th>Сумма</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan="{{ (date_range | length) + 1 }}">
                {% if my_stat.user_id == request.user.pk %}
                Мои заявки
                {% else %}
                {{ my_stat.fio }}
                {% endif %}
            </td>
            <td rowspan="{{ (date_range | length) + 1 }}">
                {% if my_stat.user_id != request.user.pk %}
                {{ my_stat.city or '' }}
                {% endif %}
            </td>
            {% for date_i in date_range %}
                {% if not loop.first %}<tr>{% endif %}
                <td>{{ date_i }}</td>
                <td>
                    {% if date_i in my_stat['dates'] %}{{ my_stat['dates'][date_i]['count'] }}{% else %}0{% endif %}
                </td>
                <td>
                    {% if date_i in my_stat['dates'] %}{{ my_stat['dates'][date_i]['revenue'] }}{% else %}0{% endif %}
                </td>
                {% if not loop.first %}</tr>{% endif %}
            {% endfor %}
            <tr>
                <td><strong>Итого</strong></td>
                <td>{{ my_stat['count'] }}</td>
                <td>{{ my_stat['revenue'] }}</td>
            </tr>
        </tr>
        {% if request.user.has_perm('cards.can_view_child') %}
        <tr>
            <td colspan="5"><strong>Заявки сотрудников</strong></td>
        </tr>
    {% for user_id, user_stat in stat.items() %}
        <tr>
            <td rowspan="{{ (date_range | length) + 1 }}">
                <a href="{{ user_stat.url }}">{{ user_stat.fio }}</a>
            </td>
            <td rowspan="{{ (date_range | length) + 1 }}">
                {{ user_stat.city or '' }}
            </td>
            {% for date_i in date_range %}
                {% if not loop.first %}<tr>{% endif %}
                <td>{{ date_i }}</td>
                <td>
                    {% if date_i in user_stat['dates'] %}{{ user_stat['dates'][date_i]['count'] }}{% else %}0{% endif %}
                </td>
                <td>
                    {% if date_i in user_stat['dates'] %}{{ user_stat['dates'][date_i]['revenue'] }}{% else %}0{% endif %}
                </td>
                {% if not loop.first %}</tr>{% endif %}
            {% endfor %}
            <tr>
                <td><strong>Итого</strong></td>
                <td>{{ user_stat['count'] }}</td>
                <td>{{ user_stat['revenue'] }}</td>
            </tr>
        </tr>
    {% endfor %}
        <tr>
            <td><strong>Всего</strong></td>
            <td></td>
            <td></td>
            <td>{{ stat_sum['count'] }}</td>
            <td>{{ stat_sum['revenue'] }}</td>
        </tr>
        <tr>
            <td>
                {% if request.user.has_perm('cards.can_view_child') %}
                <strong>ВСЕГО (мои + сотрудники)</strong>
                {% else %}
                <strong>ВСЕГО</strong>
                {% endif %}
            </td>
            <td></td>
            <td></td>
            <td>{{ stat_sum['count'] + my_stat['count'] }}</td>
            <td>{{ stat_sum['revenue'] + my_stat['revenue'] }}</td>
        </tr>
    {% endif %}
    </tbody>
    </table>
</div>
{% endblock %}

{% block js_footer %}
    {{ super() }}
    {% stylesheet 'select2' %}
    {% javascript 'select2' %}

    {% stylesheet 'daterangepicker' %}
    {% javascript 'daterangepicker' %}

    {% javascript 'finance' %}

{% endblock %}

templates/finance/list.html
{% extends 'layout.html' %}
{% block title %}Оплаты агентов{% endblock %}

{% block content %}
<div class="request-search-page">
    <h2>Оплаты агентов
        <a class="btn btn-primary btn-fill pull-right" href="{{ url('finance_pay') }}"><span class="fa fa-plus"></span> Добавить оплату</a>
    </h2>
    <div class="well request-search">
        <form class="form-horizontal" method="get" id="requests_search_form">
            <div class="form-group">
                <div class="col-lg-3 col-md-4 col-xs-12">
                    <label for="id_search_value">Дата создания</label>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                        <input type="text" class="form-control" name="daterange" value="{% if form.daterange_start.value() and form.daterange_end.value() %}{{ form.daterange_start.value() }} - {{ form.daterange_end.value() }}{% endif %}">
                        <input type="hidden" id="id_daterange_start" name="daterange_start" value="{{ form.daterange_start.value() or '' }}">
                        <input type="hidden" id="id_daterange_end" name="daterange_end" value="{{ form.daterange_end.value() or '' }}">
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-xs-12">
                    <label for="id_user">Агент</label>
                    <select id="id_user" name="user" multiple class="form-control" data-placeholder="Выберете агента" data-allow-clear="true" style="width: 100%">
                        {% for user in user_qs %}
                        <option value="{{ user[0] }}" {% if form.user.value() and user[0] in form.user.value() %}selected{% endif %}>{{ user[1] }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row form-submit">
                <div class="col-xs-12">
                    <button class="btn btn-primary btn-sm btn-fill" type="submit"><span class="fa fa-search"></span> Найти</button>
                </div>
            </div>
        </form>
    </div>
    {% include 'pagination.html' %}
    <table class="table table-condensed table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>Агент</th>
        <th>Логин</th>
        <th>Дата</th>
        <th>Сумма</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr>
            <td><a href="{{ object.user.get_absolute_url() }}">{{ object.user }}</a></td>
            <td>{{ object.user.username }}</td>
            <td>{{ object.date_created | localtime | date('SHORT_DATETIME_FORMAT') }}</td>
            <td>{{ object.subtotal }} <span class="fa fa-rub"></span></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% include 'pagination.html' %}
</div>
{% endblock %}

{% block js_footer %}
    {{ super() }}
    {% stylesheet 'select2' %}
    {% javascript 'select2' %}

    {% stylesheet 'daterangepicker' %}
    {% javascript 'daterangepicker' %}

    {% javascript 'finance' %}

{% endblock %}

templates/finance/listmy.html
{% extends 'layout.html' %}
{% block title %}Мои оплаты{% endblock %}

{% block content %}
<div class="request-search-page">
    <h2>Мои оплаты
        <abbr class="pull-right" data-toggle="popover" data-html="true" title="Помощь" data-placement="left" data-trigger="hover"
              data-content="В данном разделе вы можете видеть ваши оплаты, которые отметил у себя ваш вышестоящий партнер."
        ><span class="fa fa-question-circle-o" ></span></abbr>
    </h2>
    <div class="well request-search">
        <form class="form-horizontal" method="get" id="requests_search_form">
            <div class="form-group">
                <div class="col-lg-3 col-md-4 col-xs-12">
                    <label for="id_search_value">Дата создания</label>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                        <input type="text" class="form-control" name="daterange" value="{% if form.daterange_start.value() and form.daterange_end.value() %}{{ form.daterange_start.value() }} - {{ form.daterange_end.value() }}{% endif %}">
                        <input type="hidden" id="id_daterange_start" name="daterange_start" value="{{ form.daterange_start.value() or '' }}">
                        <input type="hidden" id="id_daterange_end" name="daterange_end" value="{{ form.daterange_end.value() or '' }}">
                    </div>
                </div>
            </div>
            <div class="row form-submit">
                <div class="col-xs-12">
                    <button class="btn btn-primary btn-sm btn-fill" type="submit"><span class="fa fa-search"></span> Найти</button>
                </div>
            </div>
        </form>
    </div>
    {% include 'pagination.html' %}
    <table class="table table-condensed table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>Дата</th>
        <th>Сумма</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr>
            <td>{{ object.date_created | localtime | date('SHORT_DATETIME_FORMAT') }}</td>
            <td>{{ object.subtotal }} <span class="fa fa-rub"></span></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% include 'pagination.html' %}
</div>
{% endblock %}

{% block js_footer %}
    {{ super() }}

    {% stylesheet 'select2' %}
    {% javascript 'select2' %}

    {% stylesheet 'daterangepicker' %}
    {% javascript 'daterangepicker' %}

    {% javascript 'finance' %}

{% endblock %}

templates/finance/pay.html
{% extends 'layout.html' %}
{% block title %}Добавление оплаты агента{% endblock %}

{% block content %}

<div class="">
    <h3>Добавление оплаты агента</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-plus"></span> Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}