dc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_change

from dashboard.views import DashboardView
from dc import settings
from users.views import EmailChangeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^email_change/$', EmailChangeView.as_view(), name='email_change'),
    url(r'^password_change/$', password_change, {'template_name': 'registration/password_change_form.html',
                                                 'post_change_redirect': 'dashboard'}, name='password_change'),

    url('^', include('django.contrib.auth.urls')),
    url('^users/', include('users.urls')),
    url('^messages/', include('alert_messages.urls')),
    url('^cards/', include('cards.urls')),
    url('^finance/', include('finance.urls')),
    url('^agreements/', include('agreements.urls')),
    url('^stantions/', include('stantions.urls')),
    url('^support/', include('support.urls', namespace='support')),

    url('^api/messages/', include('alert_messages.urls_api')),
    url('^api/cards/', include('cards.urls_api')),
    url('^api/users/', include('users.urls_api')),
    url('^api/support/', include('support.urls', namespace='support_api')),

    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stantions/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', StantionsListView.as_view(), name='stantion_list'),
    url(r'^edit/(?P<pk>[0-9]+)$', StantionsUpdateView.as_view(), name='stantion_edit'),
    url(r'^create$', StantionsCreateView.as_view(), name='stantion_create'),
    url(r'^experts/$', ExpertsListView.as_view(), name='expert_list'),
    url(r'^experts/edit/(?P<pk>[0-9]+)$', ExpertsUpdateView.as_view(), name='expert_edit'),
    url(r'^experts/create$', ExpertsCreateView.as_view(), name='expert_create'),
    url(r'^stat$', StatView.as_view(), name='stantion_stat'),
    url(r'^generator/edit$', GeneratorUpdateView.as_view(), name='generator_edit'),
]

stantions/models.py
import random

from django.db import models
from django.db.models import F, Q
from django.utils import timezone

from users.models import MyUser, City

CATEGORY_FIELD_AVAILABLE = {
    1: 'available_a',
    2: 'available_b',
    3: 'available_c',
    4: 'available_d',
    5: 'available_trailer',
}


class StantionManager(models.Manager):
    def get_available_for_user(self, user: MyUser, category: int = None):

        if user.stantion_order_type == 1:
            order = ('requests_created', 'id',)
        else:
            order = ('order', 'id',)

        user_stantion = self.filter(users__id=user.pk, active=True).order_by(*order)
        if user_stantion or user.use_only_self_stantions:
            return [stantion for stantion in user_stantion if stantion.is_allow_create(category)]
        else:
            ancestors = user.get_ancestors(ascending=True).values_list('id', 'use_only_self_stantions',
                                                                       'stantion_order_type')

            use_only_self_stantions = False

            filter_ancestor = []
            for ancestor in ancestors:
                if ancestor[1]:
                    # reset filter_ancestor and set only this user
                    filter_ancestor = [ancestor[0]]
                    use_only_self_stantions = True

                    if ancestor[2] == 1:
                        order = ('requests_created', 'id',)
                    else:
                        order = ('order', 'id',)

                    break
                else:
                    filter_ancestor.append(ancestor[0])
            if filter_ancestor:
                child_stantion = self.filter(users__id__in=filter_ancestor, active=True, is_available_for_child=True)\
                    .order_by(*order)
            if filter_ancestor and child_stantion.count():
                return [stantion for stantion in child_stantion if stantion.is_allow_create(category)]
            elif use_only_self_stantions:
                return []
            else:
                if category:
                    filter_by_category = {
                        CATEGORY_FIELD_AVAILABLE[category]: True
                    }
                else:
                    filter_by_category = {}

                return self.filter(active=True, requests_created__lt=F('daily_limit'),
                                   is_available_for_all_users=True, **filter_by_category)\
                    .filter(Q(freeze_date_end=None) | Q(freeze_date_end__lt=timezone.now()))\
                    .extra(select={'fieldsum': 'daily_limit - requests_created'}).order_by(*order)


INTERFACE_CHOICES = (
    ('eaisto', 'ЕАИСТО'),
    ('eaisto_online', 'eaisto.online'),
    ('to95', 'to95.net'),
    ('diagcard_com', 'diagcard.com'),
)


class Stantion(models.Model):
    interface = models.CharField('Интерфейс', max_length=255, blank=True, choices=INTERFACE_CHOICES, default='eaisto')
    interface_url = models.URLField('Интерфейс url', max_length=255, blank=True)
    api_key = models.CharField('Ключ для API', max_length=255, blank=True)
    active = models.BooleanField('Активна')
    freeze_date_end = models.DateTimeField('Заморозить станцию до', blank=True, null=True)
    order = models.IntegerField('№ в очереди на заполнение', help_text='Меньшее значение заполняется в первую очередь.')
    org_title = models.CharField('Организация', max_length=255)
    reg_number = models.CharField('Рег. номер', max_length=255, help_text='Регистрационный номер в реестре операторов, '
                                                                          'состоящий из пяти символов.')
    post_index = models.CharField('Индекс оператора', max_length=255, blank=True)
    city = models.ForeignKey(City, verbose_name='Город оператора', blank=True, null=True)
    address = models.CharField('Адрес оператора', max_length=255, blank=True,
                               help_text='Укажите тут улицу, дом и корпус'
                                         ' при наличии.')
    point_address = models.CharField('Адрес пункта ТО', max_length=255, blank=True, help_text='Указывать, если '
                                                                                              'отличается от адреса '
                                                                                              'оператора.')
    eaisto_login = models.CharField('Логин ЕАИСТО', blank=True, max_length=255)
    eaisto_password = models.CharField('Пароль ЕАИСТО', blank=True, max_length=255, help_text='Если оставить пустым, '
                                                                                              'то старый пароль не '
                                                                                              'изменится.')
    daily_limit = models.IntegerField('Дневной Лимит', help_text='Колличество карт, которое возможно сделать за один '
                                                                 'день.')
    available_a = models.BooleanField('Доступна кат. А', default=True, blank=True)
    available_b = models.BooleanField('Доступна кат. B', default=True, blank=True)
    available_c = models.BooleanField('Доступна кат. С', default=True, blank=True)
    available_d = models.BooleanField('Доступна кат. D', default=True, blank=True)
    available_trailer = models.BooleanField('Доступна кат. прицеп', default=True, blank=True)
    requests_created = models.IntegerField('Создано за день', blank=True, default=0)
    is_available_for_all_users = models.BooleanField('Доступно для всех', default=False)
    is_available_for_child = models.BooleanField('Доступно для потомков', default=False)
    users = models.ManyToManyField(MyUser, blank=True, verbose_name='Агент')
    auto_update = models.BooleanField('Автоматически обновлять данные', blank=True, default=False)

    objects = StantionManager()

    class Meta:
        ordering = ('order', 'id',)
        permissions = (
            ('can_change_self', 'Может изменять свои станции'),
        )

    def __str__(self):
        return self.org_title

    def is_allow_create(self, category: int = None):
        if self.freeze_date_end and self.freeze_date_end >= timezone.now():
            return False

        if category is not None:
            # test what this stantion available for this category and has limit
            return getattr(self, CATEGORY_FIELD_AVAILABLE[category]) and self.requests_created < self.daily_limit
        else:
            return self.requests_created < self.daily_limit

    def get_api_info(self):
        return {
            'interface': self.interface,
            'url': self.interface_url,
            'api_key': self.api_key,
            'eaisto_login': self.eaisto_login,
            'eaisto_password': self.eaisto_password,
        }

    def get_point_address(self):
        if self.point_address:
            return self.point_address
        else:
            point_address = ''
            if self.city:
                point_address += '{}'.format(self.city)
            if self.address:
                if point_address:
                    point_address += ', '
                point_address += '{}'.format(self.address)
            return point_address


class Expert(models.Model):
    interface = models.CharField('Интерфейс', max_length=255, blank=True, choices=INTERFACE_CHOICES, default='eaisto')
    interface_url = models.URLField('Интерфейс url', max_length=255, blank=True)
    api_key = models.CharField('Ключ для API', max_length=255, blank=True)
    last_name = models.CharField('Фамилия', max_length=255)
    first_name = models.CharField('Имя', max_length=255)
    middle_name = models.CharField('Отчество', max_length=255)
    stantion = models.ForeignKey(Stantion, verbose_name='Пункт ТО', on_delete=models.CASCADE)
    eaisto_login = models.CharField('Логин ЕАИСТО', blank=True, max_length=255)
    eaisto_password = models.CharField('Пароль ЕАИСТО', blank=True, max_length=255, help_text='Если оставить пустым, '
                                                                                              'то старый пароль не '
                                                                                              'изменится.')

    def __str__(self):
        return "{} {} {}".format(self.last_name, self.first_name, self.middle_name)

    def get_api_info(self):
        return {
            'interface': self.interface,
            'url': self.interface_url,
            'api_key': self.api_key,
            'eaisto_login': self.eaisto_login,
            'eaisto_password': self.eaisto_password,
        }


class GeneratorOperatorNum(models.Model):
    reg_number = models.IntegerField('Рег. номер',
                                     help_text='Регистрационный номер в реестре операторов, '
                                               'состоящий из пяти символов.')


class Generator(models.Model):
    is_enable_for_all = models.BooleanField('Включить генератор для всех', default=False)
    reg_nums = models.ManyToManyField(GeneratorOperatorNum)

    def get_reg_num(self):
        from cards.models import RequestAutoGenNumb
        from cards.models import Request
        while True:
            stantion_num = random.choice(self.reg_nums.values_list('reg_number', flat=True))
            diagcard_num = RequestAutoGenNumb.objects.get_card_num(stantion_num, 1)

            if not Request.objects.filter(diagcard_num=diagcard_num).count():
                break

        return diagcard_num

stantions/forms.py
from django import forms
from django.forms import modelformset_factory

from stantions.models import Stantion, Expert, Generator, GeneratorOperatorNum


class BaseEaistoPassordForm(forms.ModelForm):
    def save(self, commit=True):
        stantion = super().save(commit=False)

        update_fields = self.Meta.fields.copy()

        if not self.cleaned_data["eaisto_password"] and 'eaisto_password' in update_fields:
            update_fields.remove('eaisto_password')

        if commit:
            if stantion.pk is None:
                stantion.save()
            else:
                stantion.save(update_fields=update_fields)
            self.save_m2m()
        return stantion


class BaseStantionEditForm(BaseEaistoPassordForm):
    def save(self, commit=True):
        stantion = super().save(commit=False)

        update_fields = self.Meta.fields.copy()

        if not self.cleaned_data["eaisto_password"] and 'eaisto_password' in update_fields:
            update_fields.remove('eaisto_password')

        if 'users' in update_fields:
            update_fields.remove('users')

        if commit:
            if stantion.pk is None:
                stantion.save()
            else:
                stantion.save(update_fields=update_fields)
            self.save_m2m()
        return stantion


class StantionEditForm(BaseStantionEditForm):
    class Meta:
        model = Stantion
        fields = ['order', 'org_title', 'reg_number', 'post_index', 'city', 'address', 'point_address', 'eaisto_login',
                  'eaisto_password', 'interface_url', 'daily_limit', 'available_a', 'available_b', 'available_c',
                  'available_d', 'available_trailer', 'active']
        widgets = {
            'eaisto_password': forms.PasswordInput,
        }


class StantionEditAdminForm(BaseStantionEditForm):
    class Meta:
        model = Stantion
        fields = ['order', 'org_title', 'reg_number', 'post_index', 'city', 'address', 'point_address', 'eaisto_login',
                  'eaisto_password', 'interface_url', 'daily_limit', 'available_a', 'available_b', 'available_c',
                  'available_d', 'available_trailer', 'active', 'is_available_for_all_users', 'is_available_for_child',
                  'users']
        widgets = {
            'eaisto_password': forms.PasswordInput,
        }


class ExpertEditForm(BaseEaistoPassordForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields['stantion'].queryset = Stantion.objects.filter(users__pk=user.pk)

    class Meta:
        model = Expert
        fields = ['last_name', 'first_name', 'middle_name', 'stantion', 'eaisto_login', 'eaisto_password',
                  'interface_url', ]
        widgets = {
            'eaisto_password': forms.PasswordInput,
        }


class StatForm(forms.Form):
    daterange_start = forms.DateTimeField(label='с', input_formats=['%d.%m.%Y %H:%M'], required=True)
    daterange_end = forms.DateTimeField(label='по', input_formats=['%d.%m.%Y %H:%M'], required=True)


class GenetatorForm(forms.ModelForm):
    class Meta:
        model = Generator
        fields = ('is_enable_for_all',)


GeneratorOperatorNumFormSet = modelformset_factory(GeneratorOperatorNum, fields=('reg_number',),
                                                   widgets={'reg_number': forms.TextInput}, can_delete=True)

templates/stantions/create.html
{% extends 'layout.html' %}
{% block title %}Создание станции{% endblock %}

{% block content %}

<div class="">
    <h3>Создание станции</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" id="stantion_edit_form">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-plus"></span> Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/stantions/edit.html
{% extends 'layout.html' %}
{% block title %}Изменение станции{% endblock %}

{% block content %}

<div class="">
    <h3>Изменение станции</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" id="stantion_edit_form">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-check"></span> Сохранить</button>
                        <button type="submit" name="delete" value="true" class="btn btn-fill btn-danger"><span class="fa fa-trash"></span> Удалить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/stantions/expert_create.html
{% extends 'layout.html' %}
{% block title %}Создание эксперта{% endblock %}

{% block content %}

<div class="">
    <h3>Создание эксперта</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" id="stantion_edit_form">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-plus"></span> Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/stantions/expert_edit.html
{% extends 'layout.html' %}
{% block title %}Изменение эксперта{% endblock %}

{% block content %}

<div class="">
    <h3>Изменение эксперта</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" id="stantion_edit_form">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-check"></span> Сохранить</button>
                        <button type="submit" name="delete" value="true" class="btn btn-fill btn-danger"><span class="fa fa-trash"></span> Удалить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/stantions/expert_list.html
{% extends 'layout.html' %}
{% block title %}Эксперты{% endblock %}

{% block content %}
<div class="">
    <h3>Эксперты
        <a class="btn btn-primary btn-fill pull-right" href="{{ url('expert_create') }}"><span class="fa fa-plus"></span> Добавить эксперта</a>
    </h3>
    <br>
    <div class="row">
        <div class="col-xs-12">
            {% if object_list %}
            {% include 'pagination.html' %}
            <table class="table table-condensed table-hover table-striped">
            <thead>
            <tr>
                <th>ФИО</th>
                <th>Станция</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object }}</td>
                    <td>
                        {{ object.stantion }}
                        {% if object.stantion.active %}
                        <br><span class="label label-success">Включена</span>
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-sm btn-default" data-toggle="tooltip" title="Редактирование" href="{{ url('expert_edit',pk=object.pk) }}"><span class="fa fa-edit"></span></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
            {% include 'pagination.html' %}
            {% else %}
                <div class="alert alert-info">Эксперты не найдены</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/stantions/list.html
{% extends 'layout.html' %}
{% block title %}Станции{% endblock %}

{% block content %}
<div class="">
    <h3>Станции
        <a class="btn btn-primary btn-fill pull-right" href="{{ url('stantion_create') }}"><span class="fa fa-plus"></span> Добавить станцию</a>
    </h3>
    <br>
    <div class="row">
        <div class="col-xs-12">
            {% if object_list %}
            {% include 'pagination.html' %}
            <table class="table table-condensed table-hover table-striped">
            <thead>
            <tr>
                <th>Организация</th>
                <th>Рег. номер</th>
                <th>Адрес пункта ТО</th>
                <th>Эксперты</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        {{ object.org_title }}
                        {% if object.active %}
                        <br><span class="label label-success">Включена</span>
                        {% endif %}
                    </td>
                    <td>{{ object.reg_number }}</td>
                    <td>{{ object.point_address }}</td>
                    <td>
                        <ul class="list-unstyled">
                            {% for expert in object.expert_set.all() %}
                            <li>{{ expert }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <a class="btn btn-sm btn-default" data-toggle="tooltip" title="Редактирование" href="{{ url('stantion_edit',pk=object.pk) }}"><span class="fa fa-edit"></span></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
            {% include 'pagination.html' %}
            {% else %}
                <div class="alert alert-info">Станции не найдены</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/stantions/stat.html
{% extends 'layout.html' %}
{% block title %}Статистика{% endblock %}

{% block content %}
<div class="request-search-page">
    <h2>Статистика</h2>
    <div class="well request-search">
        <form class="form-horizontal" method="post" id="requests_search_form">
            {% csrf_token %}
            <div class="form-group">
                <div class="col-lg-4 col-md-5 col-xs-12">
                    <label for="id_search_value">Дата</label>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <span class="fa fa-calendar"></span>
                        </span>
                        <input type="text" class="form-control" name="daterange" value="{% if form.daterange_start.value() and form.daterange_end.value() %}{{ form.daterange_start.value() }} - {{ form.daterange_end.value() }}{% endif %}">
                        <input type="hidden" id="id_daterange_start" name="daterange_start" value="{{ form.daterange_start.value() or '' }}">
                        <input type="hidden" id="id_daterange_end" name="daterange_end" value="{{ form.daterange_end.value() or '' }}">
                    </div>
                </div>
            </div>
            <div class="row form-submit">
                <div class="col-xs-12">
                    <button class="btn btn-primary btn-sm btn-fill" type="submit"><span class="fa fa-check"></span> Показать</button>
                </div>
            </div>
        </form>
    </div>
    <table class="table table-condensed table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>Станция</th>
        <th>Всего карт</th>
    </tr>
    </thead>
    <tbody>

    {% for stantion_stat in stats %}
        <tr>
            <td><a href="{{ url('stantion_edit', pk=stantion_stat.stantion_id) }}">{{ stantion_stat.stantion__org_title }}</a></td>
            <td>{{ stantion_stat.req_count }}</td>
        </tr>
    {% endfor %}
        <tr>
            <td><strong>Всего</strong></td>
            <td><strong>{{ req_count_all }}</strong></td>
        </tr>
    </tbody>
    </table>
</div>
{% endblock %}

{% block js_footer %}
    {{ super() }}

    {% stylesheet 'daterangepicker' %}
    {% javascript 'daterangepicker' %}

    {% javascript 'stantion_stat' %}

{% endblock %}