dc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_change

from dashboard.views import DashboardView
from dc import settings
from users.views import EmailChangeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^email_change/$', EmailChangeView.as_view(), name='email_change'),
    url(r'^password_change/$', password_change, {'template_name': 'registration/password_change_form.html',
                                                 'post_change_redirect': 'dashboard'}, name='password_change'),

    url('^', include('django.contrib.auth.urls')),
    url('^users/', include('users.urls')),
    url('^messages/', include('alert_messages.urls')),
    url('^cards/', include('cards.urls')),
    url('^finance/', include('finance.urls')),
    url('^agreements/', include('agreements.urls')),
    url('^stantions/', include('stantions.urls')),
    url('^support/', include('support.urls', namespace='support')),

    url('^api/messages/', include('alert_messages.urls_api')),
    url('^api/cards/', include('cards.urls_api')),
    url('^api/users/', include('users.urls_api')),
    url('^api/support/', include('support.urls', namespace='support_api')),

    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import Group
from django.utils.translation import ugettext_lazy as _
from mptt.forms import TreeNodeChoiceField

from users.models import MyUser


class UserCreateFrom(forms.ModelForm):
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
    )
    groups = forms.ModelChoiceField(queryset=Group.objects.all(), label='Статус')

    def __init__(self, parent, groups, *args, **kwargs):
        super(UserCreateFrom, self).__init__(*args, **kwargs)
        self.fields['groups'].queryset = groups
        self.parent_user = parent

    class Meta:
        model = MyUser
        fields = ['username', 'password', 'fio', 'email', 'groups', 'city', 'timezone',
                  'price_a', 'price_b', 'price_c', 'price_d', 'price_trailer', 'limit_per_day', 'credit',
                  'is_test_access', 'notification_settings', 'notification_weekly_day', 'is_https', ]

    def clean_password(self):
        password = self.cleaned_data.get("password")
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password'), self.instance)
        return password

    def clean_groups(self):
        data = self.cleaned_data['groups']
        return [data]

    def clean_credit(self):
        credit = self.cleaned_data['credit']
        if not credit:
            credit = 0
        return credit

    def clean(self):
        clean_data = super().clean()

        if self.cleaned_data.get('parent'):
            parent = self.cleaned_data['parent']
        else:
            parent = self.parent_user

        if self.cleaned_data.get('notification_settings') == 'weekly' and \
                not self.cleaned_data.get('notification_weekly_day'):
            self.add_error('notification_weekly_day', 'Это поле обязательно.')

        if not parent is None:
            price_fields = ('price_a', 'price_b', 'price_c', 'price_d', 'price_trailer', )
            for field in price_fields:
                if clean_data.get(field) < getattr(self.parent_user, field):
                    self.add_error(field, 'Цена не может быть меньше, чем у вышестоящего партнера.')
        return clean_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.parent = self.parent_user
            user.save()
            # install limits
            MyUser.objects.filter(pk=user.pk).update(requests_available=user.limit_per_day)
            self.save_m2m()
        return user


class UserCreateWithMoveFrom(UserCreateFrom):
    parent = TreeNodeChoiceField(label="Вышестоящий агент", queryset=MyUser.objects.all())

    def __init__(self, to_user_qs, *args, **kwargs):
        """
        rewrite initial parent_id
        """
        super().__init__(*args, **kwargs)
        self.fields['parent'].queryset = to_user_qs

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            if self.cleaned_data['parent']:
                user.parent = self.cleaned_data['parent']

            user.save()

            # install limits
            MyUser.objects.filter(pk=user.pk).update(requests_available=user.limit_per_day)
            self.save_m2m()
        return user


class UserCreateAdminForm(UserCreateWithMoveFrom):
    use_only_self_stantions = forms.BooleanField(label="Может использовать только свои станции", required=False)
    can_delete_card = forms.BooleanField(label="Может удалять заявки", required=False)

    class Meta:
        model = MyUser
        fields = ['username', 'password', 'fio', 'email', 'groups', 'city', 'timezone',
                  'price_a', 'price_b', 'price_c', 'price_d', 'price_trailer', 'limit_per_day', 'credit',
                  'is_test_access', 'notification_settings', 'notification_weekly_day', 'is_https',
                  'stantion_order_type', ]


class UserEditForm(UserCreateFrom):
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        required=False,
        help_text=_("Введите новый пароль, чтобы изменить."),
    )
    groups = forms.ModelChoiceField(queryset=Group.objects.all(), label='Статус')

    class Meta:
        model = MyUser
        fields = ['username', 'password', 'fio', 'email', 'groups', 'city', 'timezone', 'is_active',
                  'price_a', 'price_b', 'price_c', 'price_d', 'price_trailer', 'limit_per_day', 'credit',
                  'is_test_access', 'use_only_self_stantions', 'notification_settings', 'notification_weekly_day',
                  'is_https', 'is_archive', ]

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if password:
            self.instance.username = self.cleaned_data.get('username')
            password_validation.validate_password(self.cleaned_data.get('password'), self.instance)
        return password

    def clean_groups(self):
        data = self.cleaned_data['groups']
        return [data]

    def save(self, commit=True):
        user = super().save(commit=False)

        update_fields = self.Meta.fields.copy()
        if 'groups' in update_fields:
            update_fields.remove('groups')
        if self.cleaned_data["password"]:
            user.set_password(self.cleaned_data["password"])
        elif 'password' in update_fields:
            update_fields.remove('password')
        if commit:
            user.save(update_fields=update_fields)
            self.save_m2m()
        return user


class UserEditWithMoveForm(UserEditForm):
    parent = TreeNodeChoiceField(label="Вышестоящий агент", queryset=MyUser.objects.none())

    def __init__(self, to_user_qs, *args, **kwargs):
        """
        rewrite initial parent_id
        """
        initial = kwargs.pop('initial', {})
        instance = kwargs.get('instance')
        initial['parent'] = instance.parent
        kwargs['initial'] = initial
        super().__init__(*args, **kwargs)
        self.fields['parent'].queryset = to_user_qs.exclude(pk=instance.pk)

    def save(self, commit=True):
        user = super().save(commit=False)

        update_fields = self.Meta.fields.copy()
        if 'groups' in update_fields:
            update_fields.remove('groups')
        if self.cleaned_data["password"]:
            user.set_password(self.cleaned_data["password"])
        elif 'password' in update_fields:
            update_fields.remove('password')
        if commit:
            # detect update parent
            if self.cleaned_data['parent']:
                # move only if change
                if not user.parent or self.cleaned_data['parent'].pk != user.parent_id:
                    user.parent = self.cleaned_data['parent']
                    update_fields.append('parent')
            else:
                # set root, if not root already
                if not user.is_root_node():
                    user.parent = None
                    update_fields.append('parent')

            user.save(update_fields=update_fields)
            self.save_m2m()
        return user


class UserEditAdminForm(UserEditWithMoveForm):
    use_only_self_stantions = forms.BooleanField(label="Может использовать только свои станции", required=False)
    can_delete_card = forms.BooleanField(label="Может удалять заявки", required=False)

    def __init__(self, *args, **kwargs):
        initial = kwargs.pop('initial', {})
        instance = kwargs.get('instance')
        initial['use_only_self_stantions'] = instance.use_only_self_stantions
        kwargs['initial'] = initial
        super().__init__(*args, **kwargs)

    class Meta:
        model = MyUser
        fields = ['username', 'password', 'fio', 'email', 'groups', 'city', 'timezone', 'is_active',
                  'price_a', 'price_b', 'price_c', 'price_d', 'price_trailer', 'limit_per_day', 'credit',
                  'is_test_access', 'use_only_self_stantions', 'notification_settings', 'notification_weekly_day',
                  'is_https', 'stantion_order_type', 'is_archive', ]


class UserMoveChildForm(forms.Form):
    parent = TreeNodeChoiceField(label="Вышестоящий агент", queryset=MyUser.objects.all())

    def __init__(self, user_qs, from_user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].queryset = user_qs.exclude(pk__in=from_user.get_descendants(
            include_self=True).values_list('pk'))


class UserMoveChildSelectUserForm(forms.Form):
    parent = TreeNodeChoiceField(label="Текущий вышестоящий агент", queryset=MyUser.objects.none())

    def __init__(self, to_user_qs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].queryset = to_user_qs


class UserEmailChange(forms.Form):
    password = forms.CharField(label=_("Password"), strip=False,
                               widget=forms.PasswordInput(attrs={'autofocus': ''}))
    email = forms.EmailField(label='Email')

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_password(self):
        """
        Validates that the password field is correct.
        """
        password = self.cleaned_data["password"]
        if not self.user.check_password(password):
            raise forms.ValidationError(
                _("Your old password was entered incorrectly. Please enter it again."),
                code='password_incorrect',
            )
        return password


class UserEmailAdd(forms.Form):
    email = forms.EmailField(label='Email')

dashboard/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from alert_messages.models import Message
from cards.forms import RequestEditForm
from cards.models import Request, TyreVendor
from users.forms import UserEmailAdd


class DashboardView(CreateView):
    template_name = 'dashboard.html'
    form_class = RequestEditForm
    model = Request

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_messages'] = Message.objects.filter(to_user_id=self.request.user.pk, is_read=False)
        context['last_message'] = Message.objects.filter(to_user_id=self.request.user.pk).first()
        context['requests'] = Request.objects.filter(author_id=self.request.user.pk).order_by('-date_created')[:5]
        context['tyre_vendors'] = TyreVendor.objects.all()
        context['form_add_email'] = UserEmailAdd()
        context['pay_alert_show'] = False
        if self.request.user.balance < 0:
            context['pay_alert'] = Message.objects.filter(to_user_id=self.request.user.pk, is_pay_alert=True,
                                                          is_pay_alert_hide=False).first()
            if context['pay_alert']:
                context['pay_alert_show'] = True
        return context

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save(commit=False)
        self.object.author_id = self.request.user.pk
        return super().form_valid(form)

    def get_success_url(self):

        return reverse_lazy('dashboard')

templates/dashboard.html
{% extends 'layout.html' %}
{% block content %}
    <div class="">
        <div class="row">
            <div class="col-md-6">
                {% if last_message %}
                <div class="card">
                    <div class="header">
                        <h4 class="title">Сообщение</h4>
                        <p class="category">Отправлено {{ last_message.date_send | localtime | date("SHORT_DATETIME_FORMAT") }}</p>
                    </div>
                    <div class="content">
                        {% if last_message.is_html %}
                        <p>{{ last_message.text|safe }}</p>
                        {% else %}
                        <p>{{ last_message.text }}</p>
                        {% endif %}
                    </div>
                </div>
                {% endif %}

                {% if not request.user.email_confirm_key and not request.user.is_email_confirm %}
                <div class="card">
                    <div class="content">
                        <p>Я хочу <a data-toggle="modal" href="#add_email_modal">привязать свою почту</a> для восстановления пароля и получения новостей от системы</p>
                        <p class="text-right">
                            <a class="btn btn-sm btn-warning btn-fill" data-toggle="modal" href="#add_email_modal">Привязать свою почту</a>
                        </p>
                    </div>
                </div>
                {% endif %}

            </div>

            <div class="col-md-6">
                <div class="card card-tasks tasks">
                    <div class="header">
                        <h4 class="title">Финансовая информация</h4>
                    </div>
                    <div class="content">
                        <p>Цена за карту: {{ request.user.price_b }}<span class="fa fa-rub"></span></p>
                        <p>Лимит на день:
                            {% if request.user.limit_per_day %}
                                {{ request.user.limit_per_day }} <small class="text-muted">Осталось {{ request.user.requests_available }}</small>
                            {% else %}
                                <span class="label label-default">Без ограничений</span>
                            {% endif %}
                        </p>
                        <p>Кредит:
                            {% if not request.user.credit %}
                                <span class="label label-default">Без ограничений</span>
                            {% else %}
                                {{ request.user.credit }} <small class="text-muted">Доступно {{ request.user.credit + request.user.balance }}<span class="fa fa-rub"></span></small>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>

    {% include 'messages/pay_alert_modal.html' %}
{% endblock %}
{% block js_footer %}
    {{ super() }}

    {% javascript 'dashboard' %}
    <script>
        {% if pay_alert_show %}
            jQuery(function($) {
                $('#alert_messages_pay_alert').modal('show');
            });
        {% endif %}
    </script>
{% endblock %}

templates/layout.html
<html>
<head>
    <title>{% block title %}{{ request.META['HTTP_HOST'] }}{% endblock %}</title>
    {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% endblock %}
    {% block css_framework %}
        {% stylesheet 'css_frameworks' %}
    {% endblock %}

    {% block head_css %}
        {% stylesheet 'css_main' %}
    {% endblock %}

    {% block head_js %}
    {% endblock %}
</head>
<body class="theme-{{ theme }}">

    <div class="wrapper">
        <div class="sidebar" data-color="blue" data-image="/static/components/light-bootstrap-dashboard/assets/img/sidebar-2.jpg">

            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="/" class="simple-text">
                        {{ request.META['HTTP_HOST'] }}
                    </a>
                </div>

                <ul class="nav">
                    <li {% if request.path == '/' %}class="active"{% endif %}>
                        <a href="/">
                            <i class="fa fa-home"></i>
                            <p>Главная</p>
                        </a>
                    </li>
                    <li {% if request.path.startswith(url('message_list')) or request.path.startswith('/support') %}class="active"{% endif %}>
                        <a href="{{ url('message_list') }}">
                            <i class="fa fa-envelope-o"></i>
                            <p>Сообщения <span class="badge">{{ request.user.count_unread_messages() or '' }}</span></p>
                        </a>
                    </li>
                    {% if user.has_perm('users.can_create_admin') or user.has_perm('users.can_create_manager') or user.has_perm('users.can_create_agent') %}
                     <li {% if request.path.startswith(url('users')) %}class="active"{% endif %}>
                        <a data-toggle="collapse" href="#users_links" aria-expanded="true" class="collapsed">
                            <i class="fa fa-users"></i>
                            <p>Агенты <b class="caret"></b></p>
                        </a>
                        <div class="collapse" id="users_links" aria-expanded="false">
                            <ul class="nav">
                                <li><a href="{{ url('user_create') }}">Добавить агента</a></li>
                                <li><a href="{{ url('users') }}">Мои агенты</a></li>
                                {% if user.has_perm('alert_messages.can_send_message_all_child') or user.has_perm('alert_messages.can_send_message_child') %}
                                <li><a href="{{ url('message_create') }}">Сообщение агентам</a></li>
                                {% endif %}
                                {% if user.has_perm('users.can_move_child') %}
                                <li><a href="{{ url('user_move_child_user_select') }}">Перемещение агентов</a></li>
                                {% endif %}
                                <li><a href="{{ url('users_archive') }}">Архив</a></li>
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                    <li {% if request.path.startswith(url('request_list')) %}class="active"{% endif %}>
                        <a data-toggle="collapse" href="#cards_links" aria-expanded="true" class="collapsed">
                            <i class="fa fa-file-text-o"></i>
                            <p>Заявки <b class="caret"></b></p>
                        </a>
                        <div class="collapse" id="cards_links" aria-expanded="false">
                            <ul class="nav">
                                <li><a href="{{ url('request_list') }}">Мои заявки</a></li>
                                {% if request.user.has_perm('cards.can_view_child') %}
                                <li><a href="{{ url('request_list_child') }}">Заявки агентов</a></li>
                                {% endif %}
                                <li><a href="{{ url('request_stat') }}">Упрощенная статистика</a></li>
                                <li><a href="{{ url('export_my') }}">Экспорт моих заявок</a></li>
                                {% if request.user.has_perm('cards.can_view_child') %}
                                <li><a href="{{ url('export_child') }}">Экспорт заявок агентов</a></li>
                                {% endif %}
                                <li><a href="{{ url('card_search') }}">Поиск в еаисто</a></li>
                                {% if request.user.has_perm('cards.can_card_search_mass') %}
                                <li><a href="{{ url('card_search_mass') }}">Массовый поиск в еаисто</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                    <li {% if request.path.startswith(url('finance_stat')) %}class="active"{% endif %}>
                        <a data-toggle="collapse" href="#finance_links" aria-expanded="true" class="collapsed">
                            <i class="fa fa-rub"></i>
                            <p>Финансы <b class="caret"></b></p>
                        </a>
                        <div class="collapse" id="finance_links" aria-expanded="false">
                            <ul class="nav">
                                <li><a href="{{ url('finance_stat') }}">Статистика</a></li>
                                <li><a href="{{ url('finance_stat_dynamic') }}">Динамика продаж</a></li>
                                <li><a href="{{ url('finance_my_pays_list') }}">Мои оплаты</a></li>
                                {% if request.user.has_perm('cards.can_view_child') %}
                                <li><a href="{{ url('finance_child_pays_list') }}">Оплаты агентов</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                    <li {% if request.path.startswith(url('agreement_list')) %}class="active"{% endif %}>
                        <a data-toggle="collapse" href="#agreement_links" aria-expanded="true" class="collapsed">
                            <i class="fa fa-file-text-o"></i>
                            <p>Документы <b class="caret"></b></p>
                        </a>
                        <div class="collapse" id="agreement_links" aria-expanded="false">
                            <ul class="nav">
                                <li><a href="{{ url('agreement_list') }}">Мои ДКП</a></li>
                                <li><a href="{{ url('agreement_create') }}">Добавить ДКП</a></li>
                                <li><a href="{{ STATIC_URL }}example/primer_tovarnogo_cheka.xls">Квитанция</a></li>
                            </ul>
                        </div>
                    </li>
                    {% if request.user.has_perm('stantions.can_change_self') %}
                    <li {% if request.path.startswith(url('stantion_list')) %}class="active"{% endif %}>
                        <a data-toggle="collapse" href="#station_links" aria-expanded="true" class="collapsed">
                            <i class="fa fa-user-md"></i>
                            <p>Пунты ТО <b class="caret"></b></p>
                        </a>
                        <div class="collapse" id="station_links" aria-expanded="false">
                            <ul class="nav">
                                <li><a href="{{ url('stantion_list') }}">Станции</a></li>
                                <li><a href="{{ url('expert_list') }}">Эксперты</a></li>
                                <li><a href="{{ url('stantion_stat') }}">Статистика</a></li>
                                {% if request.user.has_perm('stantions.change_generator') %}
                                <li><a href="{{ url('generator_edit') }}">Настройки генератора</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <span class="navbar-brand">{% if self.title() != request.META['HTTP_HOST'] %}{{ self.title() }}{% else %}Добро пожаловать!{% endif %}</span>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#" id="calendar_time"></a>
                            </li>
                            <!-- Authentication Links -->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <span class="avatar fa fa-user"></span> {{ request.user.get_full_name() or request.user.username }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    {% if not request.user.is_email_confirm %}
                                    <li><a data-toggle="modal" href="#add_email_modal">Привязать свою почту</a></li>
                                    {% endif %}
                                    {% if request.user.is_staff %}
                                    <li><a href="{{ url('admin:index') }}"><i class="fa fa-btn fa-wrench"></i> Админ</a></li>
                                    {% endif %}
                                    <li><a href="{{ url('user_change_print_settings_self') }}"><i class="fa fa-btn fa-wrench"></i>Настройка шапки pdf</a></li>
                                    <li><a href="{{ url('email_change') }}">Смена email</a></li>
                                    <li><a href="{{ url('password_change') }}">Смена пароля</a></li>
                                    <li><a href="/logout"><i class="fa fa-btn fa-sign-out"></i>Выход</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <div class="alert {% if message.tags %}{{ message.tags }}{% else %}alert-info{% endif %}">
                            {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>

            {% block footer %}
            <footer class="footer section-dark">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>

                            <li><a href="{{ url('support:chat_list', directory='sent') }}">Поддержка</a></li>
                            <li>
                                <a href="/">&nbsp;</a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                        &copy; 2017
                    </div>
                </div>
            </footer>
            {% endblock %}

        </div>
    </div><!-- /.container-fluid -->

<div class="modal fade" tabindex="-1" role="dialog" id="add_email_modal">
    <div class="modal-dialog" role="document">
        <form class="modal-content" action="{{ url('user_email_add') }}" method="post">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Привязывание почты</h4>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" for="id_email">Email</label>
                    <input class="form-control" id="id_email" name="email" placeholder="Email" title="" type="email" required="" value="{{ request.user.email_confirm_test or '' }}">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="submit" class="btn btn-primary btn-fill">Отправить подтверждение</button>
            </div>
        </form><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% block css_footer %}
{% endblock %}
{% block js_framework %}
    {% javascript 'js_framework' %}
{% endblock %}
{% block content_js %}
    <script type="text/javascript">
    window.csrfmiddlewaretoken = '{{ csrf_token }}';
    </script>
{% endblock %}
{% block js_footer %}
    {% javascript 'js_main' %}
{% endblock %}
</body>
</html>

templates/pagination.html
    {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous() %}
            <li>
                <a href="?{{ url_replace(request, page=page_obj.paginator.page_range[0]) }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
            {% if page == page_obj.number %}
            <li class="active"><a href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a></li>
            {% elif page_obj.number -3 <= page  <= page_obj.number +3 %}
            <li><a href="?{{ url_replace(request, page=page) }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next() %}
            <li>
                <a href="?{{ url_replace(request, page=page_obj.paginator.page_range[-1]) }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
    {% endif %}
    <div class="pagination pull-right text-muted">Всего: {{ page_obj.paginator.count }}</div>