dc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_change

from dashboard.views import DashboardView
from dc import settings
from users.views import EmailChangeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^email_change/$', EmailChangeView.as_view(), name='email_change'),
    url(r'^password_change/$', password_change, {'template_name': 'registration/password_change_form.html',
                                                 'post_change_redirect': 'dashboard'}, name='password_change'),

    url('^', include('django.contrib.auth.urls')),
    url('^users/', include('users.urls')),
    url('^messages/', include('alert_messages.urls')),
    url('^cards/', include('cards.urls')),
    url('^finance/', include('finance.urls')),
    url('^agreements/', include('agreements.urls')),
    url('^stantions/', include('stantions.urls')),
    url('^support/', include('support.urls', namespace='support')),

    url('^api/messages/', include('alert_messages.urls_api')),
    url('^api/cards/', include('cards.urls_api')),
    url('^api/users/', include('users.urls_api')),
    url('^api/support/', include('support.urls', namespace='support_api')),

    url(r'^$', DashboardView.as_view(), name='dashboard'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', UsersView.as_view(), name='users'),
    url(r'^archive$', UsersView.as_view(archive=True), name='users_archive'),
    url(r'^view/(?P<pk>[0-9]+)$', UserDetailView.as_view(), name='user_view'),
    url(r'^create/$', UserCreate.as_view(), name='user_create'),
    url(r'^edit/(?P<pk>[0-9]+)$', UserEdit.as_view(), name='user_edit'),
    url(r'^move_child/$', UserMoveChildUserSelect.as_view(), name='user_move_child_user_select'),
    url(r'^move_child/(?P<pk>[0-9]+)$', UserMoveChild.as_view(), name='user_move_child'),
    url(r'^print_settings$', UserPrintSettingsEditView.as_view(), name='user_change_print_settings_self'),
    url(r'^print_settings/(?P<pk>[0-9]+)$', UserChildPrintSettingsEditView.as_view(), name='user_change_print_settings'),
    url(r'^email_add$', EmailAddView.as_view(), name='user_email_add'),
    url(r'^email_confirm/(?P<uuid>[0-9A-Za-z\-]+)$', EmailConfirm.as_view(), name='user_email_confirm'),
]

users/models.py
import uuid
from datetime import timedelta

from decimal import Decimal
from django.contrib.auth.models import AbstractUser, UserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.db.models import F
from django.db.models.signals import pre_save
from django.utils.html import conditional_escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from mptt.fields import TreeForeignKey
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from mptt.settings import DEFAULT_LEVEL_INDICATOR

from dc import settings
from users.signals import reset_limits, archive_handler
from users.utils import PRETTY_TIMEZONE_CHOICES, get_timezone_local_name

GROUP_ADMIN_PK = 1
GROUP_MANAGER_PK = 2
GROUP_AGENT_PK = 3


class City(models.Model):
    name = models.CharField('Название', max_length=255)
    region = models.CharField('Регион', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Город'
        verbose_name_plural = 'Города'


class MyUserManager(TreeManager, UserManager):
    use_in_migrations = False


DAY_OF_THE_WEEK = (
    (1, _('Monday')),
    (2, _('Tuesday')),
    (3, _('Wednesday')),
    (4, _('Thursday')),
    (5, _('Friday')),
    (6, _('Saturday')),
    (7, _('Sunday')),
)


class MyUser(AbstractUser, MPTTModel):
    NOTIFICATION_SETTINGS_CHOICES = (
        (None, 'Без уведомлений'),
        ('weekly', 'Раз в неделю'),
        ('half_monthly', '2 раза в месяц'),
        ('monthly', 'Раз в месяц'),
    )

    ORDER_CHOICES = (
        (1, 'Равномерно'),
        (2, 'По очереди'),
    )

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        'Логин',
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    fio = models.CharField('ФИО', max_length=255)
    city = models.ForeignKey(City, null=True, verbose_name='Город', on_delete=models.SET_NULL)
    timezone = models.CharField(verbose_name='Часовой пояс', max_length=50, default=settings.TIME_ZONE,
                                choices=PRETTY_TIMEZONE_CHOICES)
    price_a = models.DecimalField('Цена кат. А', decimal_places=0, max_digits=10, default=0)
    price_b = models.DecimalField('Цена кат. B', decimal_places=0, max_digits=10, default=0)
    price_c = models.DecimalField('Цена кат. С', decimal_places=0, max_digits=10, default=0)
    price_d = models.DecimalField('Цена кат. D', decimal_places=0, max_digits=10, default=0)
    price_trailer = models.DecimalField('Цена за прицеп', decimal_places=0, max_digits=10, default=0)
    limit_per_day = models.PositiveIntegerField('Лимит на день', default=0,
                                                help_text='Если значение 0,то без ограничений')
    requests_available = models.PositiveIntegerField('Доступно заявок', default=0)
    credit = models.DecimalField('Кредит', decimal_places=0, max_digits=10, default=0, blank=True,
                                 help_text='Если значение 0,то без ограничений')
    balance = models.DecimalField('Баланс', decimal_places=0, max_digits=10, default=0)
    is_test_access = models.BooleanField('Тестовый доступ', default=False)
    is_email_confirm = models.BooleanField('Почта подтверждена', default=False)
    email_confirm_key = models.UUIDField('Ключ подтверждения почты', editable=False, blank=True, null=True,
                                         db_index=True)
    email_confirm_test = models.EmailField('Email для подтверждения', blank=True, null=True)
    use_only_self_stantions = models.BooleanField('Может использовать только свои станции', default=False, blank=True)
    can_delete_card = models.BooleanField('Может удалять заявки', default=False, blank=True)
    notification_settings = models.CharField('Уведомления об оплате', blank=True, null=True, max_length=12,
                                             choices=NOTIFICATION_SETTINGS_CHOICES)
    notification_weekly_day = models.IntegerField('День недели', blank=True, null=True, choices=DAY_OF_THE_WEEK)
    is_https = models.BooleanField('Включить защищеннное соединение (HTTPS)', default=True,
                                   help_text='При проблемах доступа к сайту, отключите эту настройку.')
    stantion_order_type = models.IntegerField('Тип очереди для станций', blank=True, default=1, choices=ORDER_CHOICES,
                                              help_text='Распостраняется только на тех, у кого есть свои станции.')
    is_archive = models.BooleanField('Архив', default=False)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    objects = MyUserManager()

    class Meta:
        permissions = (
            ('can_create_admin', 'Может создавать администраторов'),
            ('can_create_agent', 'Может создавать агентов'),
            ('can_create_manager', 'Может создавать менеджеров'),
            ('can_move_child', 'Может перемещать агентов'),
            ('can_crud_child', 'Может редактировать своих агентов'),
            ('can_crud_all_child', 'Может редактировать своих агентов и агентов агентов'),
            ('can_change_user_child_print_settings', 'Может редактировать шапки агентов'),
        )
        ordering = ('fio', 'username',)

    class MPTTMeta:
        order_insertion_by = ['username']

    def __str__(self):
        if self.fio:
            return self.fio
        else:
            return self.username

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return self.fio.strip()

    def get_short_name(self):
        """Returns the short name for the user."""
        return self.fio

    def get_label_with_level_indicator(self, minus_level=0):
        level = getattr(self, self._mptt_meta.level_attr)
        level -= minus_level
        if level < 0:
            level = 0
        indicator = mark_safe(conditional_escape(DEFAULT_LEVEL_INDICATOR) * level)
        return indicator + self.__str__()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('user_view', args=[str(self.id)])

    def is_balance_available(self, subtotal: Decimal, count: int = 1) -> bool:
        if not self.is_active:
            return False
        if (not self.limit_per_day or self.requests_available - count >= 0) and (
                    not self.credit or self.balance + self.credit - subtotal >= 0):
            return True
        else:
            return False

    def is_allow_create_request(self, subtotal: Decimal = None, count: int = 1, with_ancestors: bool = True) -> bool:
        if subtotal is None:
            subtotal = min(self.price_a, self.price_b, self.price_c, self.price_d, self.price_trailer)

        if with_ancestors:
            for ancestors in self.get_ancestors():
                if not ancestors.is_balance_available(subtotal, count):
                    return False
        return self.is_balance_available(subtotal, count)

    def decrement_request_limits(self, count: int = 1) -> None:
        """
        decrement requests_available self and all ancestors
        """
        # decrement requests_available
        if self.limit_per_day:
            self.requests_available -= count
            MyUser.objects.filter(pk=self.pk).update(requests_available=F('requests_available') - count)

        self.get_ancestors().filter(limit_per_day__gt=0).update(requests_available=F('requests_available') - count)

    def undo_decrement_request_limits(self, count: int = 1) -> None:
        """
        undo decrement requests_available self and all ancestors
        """
        # decrement requests_available
        if self.limit_per_day:
            self.requests_available += count
            MyUser.objects.filter(pk=self.pk).update(requests_available=F('requests_available') + count)

        self.get_ancestors().filter(limit_per_day__gt=0).update(requests_available=F('requests_available') + count)

    def decrement_balance(self, subtotal: Decimal, decrement_ancestors: bool = False) -> None:
        """
        decrement balance self and all ancestors
        """
        # decrement balance
        if self.credit:
            self.balance -= subtotal
            MyUser.objects.filter(pk=self.pk).update(balance=F('balance') - subtotal)
        if decrement_ancestors:
            self.get_ancestors().filter(credit__gt=0).update(balance=F('balance') - subtotal)

    def increment_balance(self, subtotal: Decimal) -> None:
        """
        increment balance
        """
        self.balance += subtotal
        MyUser.objects.filter(pk=self.pk).update(balance=F('balance') + subtotal)

    def count_unread_messages(self):
        from support.models import Chat
        return self.messages_received.filter(is_read=False).count() + Chat.objects.unread_count_support(self) \
            + Chat.objects.unread_count_user(self)

    def gen_email_confirm_key(self):
        self.email_confirm_key = uuid.uuid4()
        self.save()
        return self.email_confirm_key

    def get_print_settings(self, with_ancestors=False):
        if hasattr(self, 'print_settings'):
            return self.print_settings
        elif with_ancestors:
            for ancestors in self.get_ancestors(ascending=True).filter(print_settings__is_only_me=False):
                # get ascending with order immediate parent first, root ancestor last
                if hasattr(ancestors, 'print_settings'):
                    return ancestors.print_settings

        return None

templates/users/change_print_settings.html
{% extends 'layout.html' %}
{% block title %}Изменение шапки pdf{% endblock %}

{% block content %}

<div class="">
    <h3>Изменение шапки pdf</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal') }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-check"></span> Сохранить</button>
                        {% if show_delete %}
                        <button type="submit" name="delete" value="true" class="btn btn-fill btn-danger"><span class="fa fa-trash"></span> Удалить</button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/create.html
{% extends 'layout.html' %}
{% block title %}Добавление агента{% endblock %}

{% block content %}

<div class="">
    <h3>Добавление агента</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" id="user_form">
                {% csrf_token %}
                {{ bootstrap_form_errors(form, type='non_fields') }}
                {{  bootstrap_form(form, layout='horizontal') }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-plus"></span> Добавить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}
{% block js_footer %}
    {{ super() }}
    {% javascript 'users' %}
{% endblock %}

templates/users/edit.html
{% extends 'layout.html' %}
{% block title %}Редактирование агента {{ object.get_full_name() or object.username }}{% endblock %}

{% block content %}

<div class="">
    <h3>Редактирование агента</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal" id="user_form">
                {% csrf_token %}
                {{ bootstrap_form_errors(form, type='non_fields') }}
                {{  bootstrap_form(form, layout='horizontal',exclude='is_active, is_archive') }}
                <div class="form-group">
                    <label class="col-md-3 control-label" for="id_is_active">&nbsp;</label>
                    <div class="col-md-9">
                        <label for="id_is_active" title="Отметьте, если пользователь должен считаться активным. Уберите эту отметку вместо удаления учётной записи.">
                            <input {% if form.is_active.value() %}checked="checked"{% endif %} class="" id="id_is_active" name="is_active" type="checkbox"> Активный
                        </label>
                        <span class="help-block">
                            Отметьте, если агента должен считаться активным. Уберите эту отметку, чтобы заблокировать агента.
                        </span>
                    </div>
                </div>
                {{ bootstrap_field(form.is_archive, layout='horizontal') }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-check"></span> Сохранить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}
{% block js_footer %}
    {{ super() }}
    {% javascript 'users' %}
{% endblock %}

templates/users/list.html
{% extends 'layout.html' %}
{% block title %}Мои агенты {% if archive %}- архив{% endif %}{% endblock %}

{% block content %}
<div class="">
    <h3>Мои агенты {% if archive %}- архив{% endif %}
        {% if user.has_perm('users.can_create_admin') or user.has_perm('users.can_create_manager') or user.has_perm('users.can_create_agent') %}
        <a class="btn btn-primary btn-fill pull-right" href="{{ url('user_create') }}"><span class="fa fa-plus"></span> Добавить агента</a>
        {% endif %}
    </h3>
    <br>

    <div class="well request-search">
        <form class="form-inline" method="get" id="users_search_form">
            <input id="id_search_value" name="q" class="form-control" value="{{ request.GET.get('q') or '' }}" type="text">
            <button class="btn btn-xs btn-primary btn-sm btn-fill" type="submit"><span class="fa fa-search"></span> Найти</button>
            <button type="submit" name="export" value="true" class="btn btn-sm btn-default pull-right"><span class="fa fa-file-excel-o"></span> Экспорт</button>
        </form>
    </div>

    {% include 'pagination.html' %}
    <table class="table table-condensed table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th rowspan="2">Агент</th>
        <th rowspan="2">Логин</th>
        <th rowspan="2">Город</th>
        <th rowspan="2">Статус</th>
        <th rowspan="2">Последний вход / дата создания</th>
        <th colspan="5">Цена, <span class="fa fa-rub"></span></th>
        <th rowspan="2">Лимит на день</th>
        <th rowspan="2">Кредит</th>
        <th rowspan="2">&nbsp;</th>
    </tr>
    <tr>
        <th>A</th>
        <th>B</th>
        <th>C</th>
        <th>D</th>
        <th>Прицеп</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
        <tr {% if object.last_login_older_than(7) %}class="danger"{% elif object.last_login_older_than(3) %}class="warning"{% endif %} id="users_list_row_{{ object.pk }}">
            <td><a href="{{ url('user_view',pk=object.pk) }}" data-toggle="tooltip" title="{{ object.comment_for_user(request.user) or '' }}">{% if request.user.has_perm('users.can_crud_all_child') %}{{ object.get_label_with_level_indicator() }}{% else %}{{ object }}{% endif %}</a><br>
                {% if not object.is_active %}
                    <span class="label label-warning">Заблокирован</span>
                {% elif object.is_test_access and request.user.is_superuser %}
                    <span class="label label-default">Тестовый доступ</span>
                {% endif %}
            </td>
            <td>{{ object.username }}</td>
            <td>{{ object.city or '' }}</td>
            <td>
                <ul class="list-unstyled">
                {% for group in object.groups.all() %}
                    <li>{{ group }}</li>
                {% endfor %}
                </ul>
            </td>
            <td>{{ object.last_login | localtime | date('SHORT_DATETIME_FORMAT') }} / {{ object.date_joined | localtime | date('SHORT_DATETIME_FORMAT') }}</td>
            <td>{{ object.price_a }}</td>
            <td>{{ object.price_b }}</td>
            <td>{{ object.price_c }}</td>
            <td>{{ object.price_d }}</td>
            <td>{{ object.price_trailer }}</td>
            <td>
                {% if not object.limit_per_day %}
                    <div class="label label-default">Без ограничений</div>
                {% else %}
                    {{ object.limit_per_day }}<br>
                    <div class="label label-default">Осталось {{ object.requests_available }}</div>
                {% endif %}
            </td>
            <td>
                {% if not object.credit %}
                    <div class="label label-default">Без ограничений</div>
                {% else %}
                    {{ object.credit }}<span class="fa fa-rub"></span><br>
                    <div class="label label-default">Доступно {{ object.credit + object.balance }}<span class="fa fa-rub"></span></div>
                {% endif %}
            </td>
            <td>
                <div class="btn-group" data-toggle="tooltip" title="Редактирование">
                    <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="fa fa-pencil"></span> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url('user_edit', pk=object.pk) }}">Редактирование</a></li>
                        {% if user.has_perm('users.can_change_user_child_print_settings') %}
                            <li><a href="{{ url('user_change_print_settings', pk=object.pk) }}">Настройка шапки pdf</a></li>
                        {% endif %}
                        {% if user.has_perm('users.can_move_child') %}
                            <li><a href="{{ url('user_move_child', pk=object.pk) }}">Переместить агентов</a></li>
                        {% endif %}
                        <li><a href="#users_change_comment" data-toggle="modal" data-user-full-name="{{ object }}" data-user-id="{{ object.pk }}">Изменить комментарий</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% include 'pagination.html' %}
</div>
{% endblock %}
{% block js_footer %}
    {% include 'users/user_comment_modal.html' %}
    {{ super() }}
    <script>
    jQuery(function($) {
        $('[data-toggle="tooltip"]').tooltip();
    });
    var page = 'user_list';
    </script>
    {% javascript 'users_view' %}
{% endblock %}

templates/users/move_child.html
{% extends 'layout.html' %}
{% block title %}Перемещение агентов{% endblock %}

{% block content %}

<div class="">
    <h3>Перемещение агентов</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal">
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-check"></span> Переместить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/move_child_select_user.html
{% extends 'layout.html' %}
{% block title %}Перемещение агентов{% endblock %}

{% block content %}

<div class="">
    <h3>Перемещение агентов</h3>
    <div class="row">
        <div class="col-xs-12 col-md-7 col-lg-6">
            <form action="" method="post" class="form form-horizontal">
                <p>Выберете агента, с которого нужно переместить агентов</p>
                {% csrf_token %}
                {{  bootstrap_form(form, layout='horizontal' ) }}
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-fill btn-primary"><span class="fa fa-check"></span> Продолжить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/view.html
{% extends 'layout.html' %}
{% block title %}Агент {{ object }}{% endblock %}

{% block content %}
<div class="">
    <h1>
        {{ object }}
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="fa fa-pencil"></span> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="{{ url('user_edit', pk=object.pk) }}">Редактирование</a></li>
                {% if user.has_perm('users.can_change_user_child_print_settings') %}
                <li><a href="{{ url('user_change_print_settings', pk=object.pk) }}">Настройка шапки pdf</a></li>
                {% endif %}
                {% if user.has_perm('users.can_move_child') %}
                <li><a href="{{ url('user_move_child', pk=object.pk) }}">Переместить агентов</a></li>
                {% endif %}
                <li><a href="#users_change_comment" data-toggle="modal" data-user-full-name="{{ object }}" data-user-id="{{ object.pk }}">Изменить комментарий</a></li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </h1>
    <div class="row">
        <div class="col-lg-6 col-md-7 col-xs-12">
            <table class="table table-condensed table-striped table-user-detail">
                <tbody>
                <tr>
                    <td>Логин</td>
                    <td>
                        {{ object.username }}
                        {% if object.is_test_access and request.user.is_superuser %}
                        <br><span class="label label-default">Тестовый доступ</span>
                        {% endif %}
                        {% if not object.is_active %}
                        <br><span class="label label-warning">Заблокирован</span>
                        {% endif %}
                        {% if object.is_archive %}
                        <br><span class="label label-warning">В архиве</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>ФИО</td>
                    <td>{{ object.fio }}</td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td>{{ object.email }}</td>
                </tr>
                <tr>
                    <td>Статус</td>
                    <td>
                        <ul class="list-unstyled">
                            {% for group in object.groups.all() %}
                            <li>{{ group }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>Город</td>
                    <td>{{ object.city or '' }}</td>
                </tr>
                <tr>
                    <td>Часовой пояс</td>
                    <td>{{ object.get_timezone_local_name() }}</td>
                </tr>
                <tr>
                    <td>Баланс</td>
                    <td>{{ object.balance }}<span class="fa fa-rub"></span></td>
                </tr>
                <tr>
                    <td>Лимит на день</td>
                    <td>
                        {% if not object.limit_per_day %}
                            <span class="label label-default">Без ограничений</span>
                        {% else %}
                            {{ object.limit_per_day }}<br>
                            <span class="label label-default">Осталось {{ object.requests_available }}</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Кредит</td>
                    <td>
                        {% if not object.credit %}
                            <span class="label label-default">Без ограничений</span>
                        {% else %}
                            {{ object.credit }}<span class="fa fa-rub"></span><br>
                            <div class="label label-default">Доступно {{ object.credit + object.balance }}<span class="fa fa-rub"></span></div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Уведомления об оплате</td>
                    <td>{{ object.get_notification_settings_display() }}{% if object.notification_settings == 'weekly' %} в {{ object.get_notification_weekly_day_display() or '' }}{% endif %}</td>
                </tr>

                <tr>
                    <td>Последний вход</td>
                    <td>{{ object.last_login | localtime | date('SHORT_DATETIME_FORMAT') }}</td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td>{{ object.date_joined | localtime | date('SHORT_DATETIME_FORMAT') }}</td>
                </tr>

                {% if request.user.has_perm('users.can_crud_all_child') and object.parent %}
                <tr>
                    <td>Вышестоящий агент</td>
                    {% if request.user.is_superuser or object.parent.pk != request.user.pk %}
                    <td><a href="{{ object.parent.get_absolute_url() }}">{{ object.parent }}</a></td>
                    {% elif object.parent.pk == request.user.pk %}
                    <td>{{ object.parent }}</td>
                    {% endif %}
                </tr>
                {% endif %}
                <tr>
                    <td>Комментарий</td>
                    <td id="user_comment">{{ object.comment_for_user(request.user) or '' }}</td>
                </tr>
                </tbody>
            </table>
            <h5>Цены:</h5>
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>A</th>
                    <th>B</th>
                    <th>C</th>
                    <th>D</th>
                    <th>Прицеп</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ object.price_a }}</td>
                    <td>{{ object.price_b }}</td>
                    <td>{{ object.price_c }}</td>
                    <td>{{ object.price_d }}</td>
                    <td>{{ object.price_trailer }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        {% if child_users_iter %}
        <div class="col-lg-6 col-md-7 col-xs-12">
            <h5>Агенты:</h5>
            <ul>
                {% for user, item_descr in child_users_iter %}
                    <li>
                        <a href="{{ user.get_absolute_url() }}">{{ user.get_label_with_level_indicator(object.get_level()+1) }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block js_footer %}
    {% include 'users/user_comment_modal.html' %}
    {{ super() }}
    <script>
    var page = 'user_view';
    </script>
    {% javascript 'users' %}
    {% javascript 'users_view' %}
{% endblock %}